---

name: Build
on: [push, pull_request]
jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false

      matrix:
        os: [ubuntu-latest, ubuntu-22.04, macOS-14, macOS-15]
        compiler: [gcc, clang]
        exclude:
          - os: macOS-14
            compiler: gcc
          - os: macOS-15
            compiler: gcc

    steps:
      - uses: actions/checkout@v4

      - name: Install libpcap-dev
        if: contains(matrix.os, 'ubuntu')
        run: sudo apt install -y libpcap-dev

      - name: Compile using ${{ matrix.compiler }}
        run: make CC=${{ matrix.compiler }}

      - name: Install
        run: sudo make install

      - name: Execute
        run: /usr/local/sbin/ifpstat -v

...
